export const FSII_INDIGENOUS_IDENTITY_VALUES = [
    "Not applicable",
    "First Nations (Status/Non-Status)",
    "Métis",
    "Inuk (Inuit)",
] as const;

export type FsiiIndigenousIdentity = (typeof FSII_INDIGENOUS_IDENTITY_VALUES)[number];

export const FSII_ACCESSIBILITY_DIFFICULTY_VALUES = [
    "Yes, sometimes",
    "Yes, often",
    "No",
] as const;

export type FsiiAccessibilityDifficulty =
    (typeof FSII_ACCESSIBILITY_DIFFICULTY_VALUES)[number];

export const FSII_OTHER_GENDER_MAX_LENGTH = 150;

export const FSII_NEIGHBOURHOOD_VALUES = [
    "Abbeydale",
    "Acadia",
    "Albert Park/Radisson Heights",
    "Altadore",
    "Applewood Park",
    "Arbour Lake",
    "Aspen Woods",
    "Auburn Bay",
    "Banff Trail",
    "Bankview",
    "Bayview",
    "Beddington Heights",
    "Bel-Aire",
    "Belmont",
    "Beltline",
    "Belvedere",
    "Bonavista Downs",
    "Bowness",
    "Braeside",
    "Brentwood",
    "Bridgeland/Riverside",
    "Bridlewood",
    "Brittania",
    "Cambrian Heights",
    "Canyon Meadows",
    "Capitol Hill",
    "Carrington",
    "Castleridge",
    "Cedarbrae",
    "CFB - Lincoln Park PMQ",
    "Chaparral",
    "Charleswood",
    "Chinatown",
    "Chinook Park",
    "Christie Park",
    "Citadel",
    "Cityscape",
    "Cliff Bungalow",
    "Coach Hill",
    "Collingwood",
    "Copperfield",
    "Coral Springs",
    "Cougar Ridge",
    "Country Hills",
    "Country Hills Village",
    "Coventry Hills",
    "Cranston",
    "Crescent Heights",
    "Crestmont",
    "Currie Barracks",
    "Dalhousie",
    "Deer Ridge",
    "Deer Run",
    "Diamond Cove",
    "Discovery Ridge",
    "Don't Know",
    "Douglasdale/Glen",
    "Dover",
    "Downtown Commercial Core",
    "Downtown East Village",
    "Downtown West End",
    "Eagle Ridge",
    "Eau Claire",
    "Edgemont",
    "Elbow Park",
    "Elboya",
    "Erin Woods",
    "Erlton",
    "Evanston",
    "Evergreen",
    "Fairview",
    "Falconridge",
    "Forest Heights",
    "Forest Lawn",
    "Forest Lawn Industrial",
    "Garrison Green",
    "Garrison Woods",
    "Glamorgan",
    "Glenbrook",
    "Glendale",
    "Greenview",
    "Greenwood/Greenbriar",
    "Hamptons",
    "Harvest Hills",
    "Hawkwood",
    "Haysboro",
    "Hidden Valley",
    "Highland Park",
    "Highwood",
    "Hillhurst",
    "Homestead",
    "Hounsfield Heights/Briar Hill",
    "Huntington Hills",
    "Inglewood",
    "Kelvin Grove",
    "Keystone Hills",
    "Killarney/Glengarry",
    "Kincora",
    "Kingsland",
    "Lake Bonavista",
    "Lakeview",
    "Legacy",
    "Lincoln Park",
    "Livingston",
    "Lower Mount Royal",
    "Macewan Glen",
    "Mahogany",
    "Manchester",
    "Maple Ridge",
    "Marlborough",
    "Marlborough Park",
    "Martindale",
    "Mayfair",
    "Mayland Heights",
    "McKenzie Lake",
    "McKenzie Towne",
    "Meadowlark Park",
    "Midnapore",
    "Millrise",
    "Mission",
    "Monterey Park",
    "Montgomery",
    "Mount Pleasant",
    "New Brighton",
    "Nolan Hill",
    "North Glenore Park",
    "North Haven",
    "North Haven Upper",
    "Oakridge",
    "Ogden",
    "Outside of Calgary",
    "Palliser",
    "Panorama Hills",
    "Parkdale",
    "Parkhill",
    "Parkland",
    "Patterson",
    "Penbrooke Meadows",
    "Pineridge",
    "Point McKay",
    "Pump Hill",
    "Queens Park Village",
    "Queensland",
    "Ramsay",
    "Ranchlands",
    "Red Carpet",
    "Redstone",
    "Renfrew",
    "Richmond",
    "Rideau Park",
    "Riverbend",
    "Rocky Ridge",
    "Rosedale",
    "Rosemont",
    "Rosscarrock",
    "Roxboro",
    "Royal Oak",
    "Royal Vista",
    "Rundle",
    "Rutland Park",
    "Saddle Ridge",
    "Sage Hill",
    "Sandstone Valley",
    "Scarboro",
    "Scarboro/Sunalta West",
    "Scenic Acres",
    "Seton",
    "Shaganappi",
    "Shawnee Slopes",
    "Shawnessy",
    "Shepard Industrial",
    "Sherwood",
    "Signal Hill",
    "Silver Springs",
    "Silverado",
    "Skyview Ranch",
    "Somerset",
    "South Calgary",
    "Southview",
    "Southwood",
    "Springbank Hill",
    "Spruce Cliff",
    "St. Andrews Heights",
    "Strathcona Park",
    "Sunalta",
    "Sundance",
    "Sunnyside",
    "Taradale",
    "Temple",
    "Thorncliffe",
    "Tuscany",
    "Tuxedo Park",
    "University District",
    "University Heights",
    "University of Calgary",
    "Upper Mount Royal",
    "Valley Ridge",
    "Varsity",
    "Vista Heights",
    "Walden",
    "West Hillhurst",
    "West Springs",
    "Westgate",
    "Whitehorn",
    "Wildwood",
    "Willow Park",
    "Windsor Park",
    "Winston Heights/Mountview",
    "Wolf Willow",
    "Woodbine",
    "Woodlands",
    "Yorkville",
    "Mount Royal",
    "Radisson Heights",
    "Alpine Park",
    "Ambleton",
    "Cornerstone",
    "Great Plains",
    "Haskayne",
    "Hotchkiss",
    "Lewisburg",
    "Pine Creek",
    "Rangeview",
    "Starfield",
    "Stonegate Landing",
    "Twinhills",
] as const;

export type FsiiNeighbourhood =
    (typeof FSII_NEIGHBOURHOOD_VALUES)[number];

export const FSII_MAIN_LANGUAGE_VALUES = [
    "English",
    "French",
    "An Indigenous language",
    "Cantonese",
    "Dinka",
    "Farsi",
    "Hindi",
    "Korean",
    "Kurdish",
    "Mandarin",
    "Nuer",
    "Pashto",
    "Polish",
    "Punjabi",
    "Somali",
    "Spanish",
    "Tagalog",
    "Urdu",
    "Vietnamese",
    "Other",
    "Arabic",
    "Don't Know",
] as const;

export type FsiiMainLanguage =
    (typeof FSII_MAIN_LANGUAGE_VALUES)[number];

export const FSII_POPULATION_GROUP_VALUES = [
    "Indigenous (First Nations, Metis, Inuit)",
    "African/Caribbean",
    "Chinese",
    "Filipino",
    "Japanese",
    "Korean",
    "Latin American",
    "South Asian (Indian, Pakistani, Sri Lankan, etc.)",
    "Southeast Asian (Vietnamese, Cambodian, Thai, Laotian, etc.)",
    "If more than one group not listed, write other population group(s)",
    "Arab/West Asian",
    "White",
] as const;

export type FsiiPopulationGroup =
    (typeof FSII_POPULATION_GROUP_VALUES)[number];

export const FSII_BIRTH_COUNTRY_VALUES = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antigua And Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia-Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo, Democratic Republic Of The (Zaire)",
    "Congo, Republic Of",
    "Cook Islands",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe (French)",
    "Guam (Usa)",
    "Guatemala",
    "Guinea",
    "Guinea Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast (Cote D`Ivoire)",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique (French)",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia (French)",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "North Korea",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestinian Authority",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn Island",
    "Poland",
    "Polynesia (French)",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Helena",
    "Saint Kitts And Nevis",
    "Saint Lucia",
    "Saint Pierre And Miquelon",
    "Saint Vincent And Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome And Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia And South Sandwich Islands",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard And Jan Mayen Islands",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste (East Timor)",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad And Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks And Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Unknown",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Virgin Islands",
    "Wallis And Futuna Islands",
    "Yemen",
    "Zambia",
    "Zimbabwe",
] as const;

export type FsiiBirthCountry =
    (typeof FSII_BIRTH_COUNTRY_VALUES)[number];

export const FSII_HOUSING_SITUATION_VALUES = [
    "Stable housing",
    "Temporary housing",
    "Couch surfing",
    "Shelter",
    "No shelter, sleeping rough",
    "Other",
] as const;

export type FsiiHousingSituation =
    (typeof FSII_HOUSING_SITUATION_VALUES)[number];


export function isFsiiIndigenousIdentity(
    value: string,
): value is FsiiIndigenousIdentity {
    return FSII_INDIGENOUS_IDENTITY_VALUES.includes(value as FsiiIndigenousIdentity);
}

export function isFsiiAccessibilityDifficulty(
    value: string,
): value is FsiiAccessibilityDifficulty {
    return FSII_ACCESSIBILITY_DIFFICULTY_VALUES.includes(
        value as FsiiAccessibilityDifficulty,
    );
}

export function isIsoCalendarDate(value: string): boolean {
    const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
    if (!match) return false;

    const year = Number(match[1]);
    const month = Number(match[2]);
    const day = Number(match[3]);
    const date = new Date(Date.UTC(year, month - 1, day));
    return date.getUTCFullYear() === year &&
        date.getUTCMonth() === month - 1 &&
        date.getUTCDate() === day;
}

export function isIsoCalendarMonth(value: string): boolean {
    if (/^\d{4}$/.test(value)) return true;
    if (/^\d{2}$/.test(value)) {
        const month = Number(value);
        return month >= 1 && month <= 12;
    }
    const match = /^(\d{4})-(\d{2})$/.exec(value);
    if (!match) return false;
    const month = Number(match[2]);
    return month >= 1 && month <= 12;
}

export function isGradeInSchool(value: string): boolean {
    return /^(?:[1-9]|1[0-2])$/.test(value);
}
